### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by isuruf** [certik/scipy-2016-symengine-talk#1]
What should be the CMake options be for benchmarking?
For example,

WITH_FLINT=yes
INTEGER_CLASS=flint
WITH_PIRANHA=yes

**Comment by certik** [comment]
And also `-DWITH_TCMALLOC=ON`, that one is important. Is the flint integer class currently the fastest?

**Comment by isuruf** [comment]
Yes. I'm not sure if using `-DWITH_TCMALLOC=ON` would affect Python wrappers, because of different mallocs used

**Comment by isuruf** [comment]
Flint integer class is the fastest.

**Comment by certik** [comment]
We need to try it out. I think we link with tcmalloc explicitly, so perhaps the wrappers won't get affected. There might be a way to specify our own C++ allocators and in them call the tcmalloc directly, so that it doesn't collide with Python malloc.

**Comment by isuruf** [comment]
For the compiler, I can use gcc or clang or icpc. Which should I use?
Also I can benchmark with Ginac, Mathematica and Maple

**Comment by certik** [comment]
We need to try the compilers. The default gcc options should be the fastest. Make sure you use a recent version. I have no idea how clang does compared to gcc, it might be a bit slower, we'll see. Icpc might actually be faster than gcc, again, we need to try it out.

**Comment by abhinavagarwal07** [comment]
```
./expand6 100 28.0
./expand6 200 99.0
./expand6 300 229.0
./expand6 400 427.0
./expand6 500 631.0
./expand6 600 1090.0
./expand6 700 1440.0
./expand6 800 2276.0
./expand6 900 2861.0
./expand6 1000 3650.0
[28.0, 99.0, 229.0, 427.0, 631.0, 1090.0, 1440.0, 2276.0, 2861.0, 3650.0]
/bin/sh: 1: ./expand6_ginac: not found
Traceback (most recent call last):
  File "B.py", line 23, in <module>
    time[i] = float(output.splitlines()[0].decode('utf-8').replace("ms", "").strip())
IndexError: list index out of range
```

getting this error

**Comment by isuruf** [comment]
You need to compile the ginac benchmarks. `expand6_ginac.cpp`, `expand7_ginac.cpp`, `expand2_ginac.cpp`.

**Comment by abhinavagarwal07** [comment]
how to compile them ?

**Comment by isuruf** [comment]
You need to install ginac. (libginac_dev package in debian)
Exact command to compile the source files is in a comment at the top of each file.

**Comment by abhinavagarwal07** [comment]
Thanks
so we should write equivalent test for `sympy` etc like expands for beginner.

**Comment by isuruf** [comment]
SymPy benchmarks are here, https://github.com/symengine/symengine.py/tree/master/benchmarks
